# Introduction to Tensors , manipulating tensors, tensors and numpy and @tf.function.

In [ ]:
@Author: KishanMishra

In [29]:
#Import tensorflow
import warnings
warnings.filterwarnings("ignore")
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.10.0


In [6]:
# Creating scalar with tf.constant()

scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
#Check dimension of the scalar

scalar.ndim

0

In [8]:
#Creating a vector

vector=tf.constant([1,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [9]:
#Checking dimension of the vector

vector.ndim

1

In [10]:
#Creating a matrix

mat=tf.constant([[1,2],[3,4]])
mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [11]:
#Checking dimension of the matrix

mat.ndim

2

In [14]:
#Creating another matrix

mat2=tf.constant([[1.,2.],
                  [3.,4],
                  [5.,8]],dtype=tf.float16)
mat2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 8.]], dtype=float16)>

In [17]:
#Checking dimension of the matrix

mat2.ndim

2

In [18]:
#Now lets create a tensor (x,y,z)

tensor=tf.constant([[[1,2,3],[2,3,4]],[[5,6,7],[8,9,10]],[[11,12,13],[14,15,16]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  3,  4]],

       [[ 5,  6,  7],
        [ 8,  9, 10]],

       [[11, 12, 13],
        [14, 15, 16]]], dtype=int32)>

In [19]:
#Here shape=(3, 2, 3) 3-> No of matrixs , 2-> no of rows in each matrix , 3-> no of columns in each matrix
#Checking dimension of a tensor
tensor.ndim

3

# Conclusion

1. Scalar -> a single number.
2. Vector -> a number with direction e.g wind-speed.
3. Matrix -> a 2-dimensional array of numbers
4. Tensor -> a n-dimensional array of numbers

# Creating tensor with `tf.Variable`

In [22]:
#Creating the same tensor with tf.Variable

tensor1=tf.Variable([10,7]) #changeable
tensor1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [23]:
tensor1[0].assign(5)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([5, 7], dtype=int32)>

# Creating random tensors

In [25]:
#Random tensors are tensors with some arbitary sizes.
# Create random tensors

random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2)) #normal distribution

random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [27]:
#Shuffle a tensor or shuffle your data

not_shuffled=tf.constant([[10,7],[2,5],[3,7]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  7]], dtype=int32)>

In [32]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  7],
       [ 2,  5]], dtype=int32)>

In [43]:
tf.random.set_seed(42) #global level random seed
tf.random.shuffle(not_shuffled,seed=42) #will result to same order everytime

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  7]], dtype=int32)>

# Other ways of making tensors

In [46]:
#Create tensors of all ones

tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [50]:
#Create tensors of all zeroes

tf.zeros(shape=(10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

# Turn numpy arrays to tensors

In [56]:
import numpy as np

nparray=np.arange(1,25,dtype=np.int32)

In [58]:
A=tf.constant(nparray,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [59]:
A.ndim

3

# Getting Information from Tensors

1. SHAPE
2. AXIS
3. RANK
4. SIZE

In [61]:
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [64]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)#size=(2*3*4*5)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [72]:
print('Datatype of every element :',rank_4_tensor.dtype)
print('Number of dimensions or rank:',rank_4_tensor.ndim)
print('Shape of tensor :',rank_4_tensor.shape)
print('Total number of elements in a tensor :',tf.size(rank_4_tensor).numpy())

Datatype of every element : <dtype: 'float32'>
Number of dimensions or rank: 4
Shape of tensor : (2, 3, 4, 5)
Total number of elements in a tensor : 120


# Indexing Tensors

In [82]:
#Get the first two elements from each dimensions

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [81]:
#get the first element from each dimension except the last one

rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [92]:
#Create a rank 2 tensor

np2=np.arange(1,7)
rank2_tensor=tf.constant(np2,shape=(3,2))
rank2_tensor

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [96]:
#Last item of each row

rank2_tensor[:,-1]

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 4, 6])>

# Expanding Tensors

In [102]:
rank_3_tensor=rank2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(3, 2, 1), dtype=int64, numpy=
array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])>

In [104]:
# Alternative

tf.expand_dims(rank2_tensor,axis=1)

<tf.Tensor: shape=(3, 1, 2), dtype=int64, numpy=
array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])>

# Basic Operations on Tensors

In [4]:
tensor=tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [5]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [6]:
tensor-2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 5],
       [1, 2]], dtype=int32)>

In [8]:
# Tensorflow builtin functions

tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [9]:
tf.math.add(tensor,6)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 13],
       [ 9, 10]], dtype=int32)>

# Matrix Multiplication

In [12]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [13]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [12]:
# Create one tensor with (3x2) shape

tensor1=tf.constant([[1,2],[3,4],[5,6]])
tensor1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [5]:
# Create another tensor with (2X3) shape

tensor2=tf.constant([[1,2,3],[4,5,6]])
tensor2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [6]:
tf.matmul(tensor1,tensor2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

# You can reshape a tensor using `tf.reshape()`

In [9]:
tf.reshape(tensor2,shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [14]:
#Lets do more trials

X=tf.constant([[1,2,3],[4,5,6]])
Y=tf.constant([[7,8,9],[5,6,7]])
X,Y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[7, 8, 9],
        [5, 6, 7]], dtype=int32)>)

In [15]:
X@Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [2,3], In[1]: [2,3] [Op:MatMul]

In [17]:
X @ tf.reshape(Y,shape=(3,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 43,  39],
       [109,  99]], dtype=int32)>

In [18]:
tf.matmul(X,tf.reshape(Y,shape=(3,2)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 43,  39],
       [109,  99]], dtype=int32)>

In [19]:
# Lets try transposing

In [21]:
tf.transpose(Y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[7, 5],
       [8, 6],
       [9, 7]], dtype=int32)>

In [24]:
X @ tf.transpose(Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 50,  38],
       [122,  92]], dtype=int32)>

# The Dot Product

In [4]:
#Perform the dot product using tensordot()

x=tf.constant([[1,2],[3,4],[5,6]])
y=tf.constant([[7,8],[9,1],[3,4]])
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[7, 8],
        [9, 1],
        [3, 4]], dtype=int32)>)

In [8]:
tf.tensordot(tf.transpose(x),y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[49, 31],
       [68, 44]], dtype=int32)>

In [10]:
#Checking by transposing x

tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[49, 31],
       [68, 44]], dtype=int32)>

In [11]:
#Checking by reshaping x

tf.matmul(tf.reshape(x,shape=(2,3)),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[34, 22],
       [91, 61]], dtype=int32)>

In [ ]:
# While both transpose and reshape do the same work why our value matrix getting incorrect.

In [15]:
print('Normal X \n',x,'\n')
print('Transpose X\n',tf.transpose(x),'\n')
print('Reshaped X\n',tf.reshape(x,shape=(2,3)),'\n')

Normal X 
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32) 

Transpose X
 tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32) 

Reshaped X
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32) 



In [16]:
# So here reshape method is reshaping the matrix with random elements, which results us incorrect result.

In [17]:
# So the correct way of matrix multiplication is by using transpose

tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[49, 31],
       [68, 44]], dtype=int32)>

# Changing the datatype of a tensor

In [18]:
B=tf.constant([1.4,5.4])
B.dtype

tf.float32

In [19]:
# Change the datatype from float32 to float16

B=tf.cast(B,dtype=tf.float16)
B.dtype

tf.float16

In [20]:
# Lets chnage one integer typw to float type

C=tf.constant([4,5])
C.dtype

tf.int32

In [24]:
C=tf.cast(C,dtype=tf.float32)
C.dtype

tf.float32

# Aggregating Tensors

In [25]:
# Get the absolute Value

A=tf.constant([-7,-10])
tf.abs(A)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [32]:
# Random Tensor

A=tf.constant(np.random.randint(0,100,size=50))
A

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([11, 16, 62, 34, 91, 10, 39, 30,  9, 19, 35,  6, 55, 64, 62, 17, 39,
       69, 54,  2, 65, 26, 90,  3, 14, 84, 28, 47, 89, 52, 55, 38, 13,  8,
       75, 94, 83, 60, 83, 80,  5, 71, 33, 86, 68, 55, 67, 95, 65, 41])>

In [33]:
# Get minimum number

tf.reduce_min(A)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [34]:
# Get maximum number

tf.reduce_max(A)

<tf.Tensor: shape=(), dtype=int64, numpy=95>

In [35]:
#Get mean number

tf.reduce_mean(A)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [36]:
# Get sum of tensor

tf.reduce_sum(A)

<tf.Tensor: shape=(), dtype=int64, numpy=2397>

In [43]:
#Get variance of tensor

import tensorflow_probability as tfp

In [45]:
tfp.stats.variance(A)

<tf.Tensor: shape=(), dtype=int64, numpy=818>

In [47]:
# Get standard deviation of tensor

tf.math.reduce_std(tf.cast(A,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.589094>

# Find the positional maximum and minimum

In [55]:
mat=tf.random.Generator.from_seed(42)
mat=mat.uniform(shape=[50])

In [56]:
mat

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.7493447 , 0.73561966, 0.45230794, 0.49039817, 0.1889317 ,
       0.52027524, 0.8736881 , 0.46921718, 0.63932586, 0.6467117 ,
       0.96246755, 0.41009164, 0.86540747, 0.8862978 , 0.27795732,
       0.8857763 , 0.2179842 , 0.29115117, 0.03953862, 0.8136791 ,
       0.8139852 , 0.52180684, 0.12496924, 0.5488483 , 0.7755773 ,
       0.6184403 , 0.24936223, 0.89341843, 0.28422844, 0.70332646,
       0.2622137 , 0.4432162 , 0.466465  , 0.05981874, 0.40098202,
       0.69292355, 0.1284684 , 0.22770369, 0.33691216, 0.5329138 ,
       0.5914326 , 0.21738243, 0.5322075 , 0.05148339, 0.03951418,
       0.41866875, 0.78939915, 0.04384279, 0.96955836, 0.49116182],
      dtype=float32)>

In [57]:
# Find positional Maximum

tf.argmax(mat)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [58]:
mat[tf.argmax(mat)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.96955836>

In [59]:
#Check for equality

mat[tf.argmax(mat)]==tf.reduce_max(mat)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [60]:
# Find positional minimum

tf.argmin(mat)

<tf.Tensor: shape=(), dtype=int64, numpy=44>

# Squeezing of a tensor

In [65]:
tf.random.Generator.from_seed(42)

mat2=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,50))
mat2

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.52757955, 0.77752113, 0.08844841, 0.15435421, 0.03486443,
          0.9594854 , 0.00204885, 0.846756  , 0.11929381, 0.2680657 ,
          0.904192  , 0.23151124, 0.80755043, 0.6290171 , 0.48629987,
          0.43332565, 0.9778489 , 0.44615293, 0.4113754 , 0.11549258,
          0.01439643, 0.663712  , 0.08440328, 0.35622096, 0.40787733,
          0.20541596, 0.5289309 , 0.9864435 , 0.15637183, 0.90673244,
          0.7785406 , 0.2240212 , 0.69857526, 0.4384842 , 0.986079  ,
          0.3382069 , 0.13191617, 0.14559841, 0.15423548, 0.18280828,
          0.39811885, 0.2816844 , 0.71723723, 0.04827571, 0.30017304,
          0.75026035, 0.19027877, 0.6722808 , 0.6812177 , 0.01912212]]]],
      dtype=float32)>

In [67]:
mat2_squeezed=tf.squeeze(mat2)
mat2_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.52757955, 0.77752113, 0.08844841, 0.15435421, 0.03486443,
       0.9594854 , 0.00204885, 0.846756  , 0.11929381, 0.2680657 ,
       0.904192  , 0.23151124, 0.80755043, 0.6290171 , 0.48629987,
       0.43332565, 0.9778489 , 0.44615293, 0.4113754 , 0.11549258,
       0.01439643, 0.663712  , 0.08440328, 0.35622096, 0.40787733,
       0.20541596, 0.5289309 , 0.9864435 , 0.15637183, 0.90673244,
       0.7785406 , 0.2240212 , 0.69857526, 0.4384842 , 0.986079  ,
       0.3382069 , 0.13191617, 0.14559841, 0.15423548, 0.18280828,
       0.39811885, 0.2816844 , 0.71723723, 0.04827571, 0.30017304,
       0.75026035, 0.19027877, 0.6722808 , 0.6812177 , 0.01912212],
      dtype=float32)>

# One Hot Encoding

In [70]:
colors=[0,1,2]

tf.one_hot(colors,depth=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [71]:
# Tensor and Numpy

In [72]:
# Create a tensor from numpy array

tensor1=tf.constant(np.array([1,2,3,4,5]))
tensor1

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 2, 3, 4, 5])>

In [73]:
#Convert tensor back to numpy array

np.array(tensor1)

array([1, 2, 3, 4, 5])

In [74]:
tensor1.numpy()

array([1, 2, 3, 4, 5])

In [77]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [76]:
!nvidia-smi

zsh:1: command not found: nvidia-smi
